### ISSUE TITLE
Multiple connection to Server or Router

### ISSUE THREAD

**Issue by Uskok** [epsilonrt/libmodbuspp#6]
Hi,

how can I make multiple connections to the server/router in the same time? I try to connect two masters (QModMaster installed on two computers) but only first connection is able to collect data. From the source or example I am not able to find what to do.
Testing environment: 
Ubuntu 18.04 where the sources are installed and compiled
Windows 10 for master part (QModMaster )
Thank in advance.

    Boris

**Comment by epsilonrt** [comment]
Have you read carefully the comments of the [router-simple](https://github.com/epsilonrt/libmodbuspp/blob/master/examples/router/router-simple/main.cpp) example program?

**Comment by Uskok** [comment]
Thank you for you fast response. I couldn't test with your suggested example I tried  the simplest clock-server when I got stuck in my analysis. How I can make two or more masters connected to clock-server in the same time? I would appreciate your help.

**Comment by epsilonrt** [comment]
Once again what you are asking is totally inconsistent. The modbus protocol is a master-slave protocol: there can only be one master at a given time on a link. Thank you for documenting yourself by reading the reference documents on [mordbus.org](https://modbus.org/specs.php), after if you wish we can discuss possible things ...

**Comment by Uskok** [comment]
In the documentation of the libmodbus is example how to connect multiple masters on the same slave/server over TCP. The base socket communication has no different using in Modbus, IEC61850, web, or any other client/server approach. I'm just trying to politely ask if that's possible with your library.

**Comment by epsilonrt** [comment]
As far as I am concerned, I always refer to the reference documentation, so it is not because an implementation has made non-standard choices that I should do the same. So concurrent access (parallel) to a meaningless slave, this has not been implemented in libmodbuspp. So I advise you to use libmodbus if you want to do this sort of thing.

**Comment by Uskok** [comment]
Thank you for your support.
