### ISSUE TITLE
Unreachable serial port configuration

### ISSUE THREAD

**Issue by zkasa** [epsilonrt/libmodbuspp#8]
Hi!
It is not possible to get configuration '9600 8 N 1'. E parity is always used.

**Comment by Northpower** [comment]
Hi, I have the same problem.
I want to configure the Modbus Rtu setting to 9600N1 but you write that the possible combinations for PS are E1, O1 and N2. We are missing the N1. If you will add N1 you will be my hero :). And happy new year :D

**Comment by epsilonrt** [comment]
Hi, 
As specified in the MODBUS OSL standard https://modbus.org/docs/Modbus_over_serial_line_V1_02.pdf, page 12, if no parity, there must be 2 stop bits in order to guarantee that the duration of a character is 11 bits.
